# from grpc import protos_and_services

# HTTP Request Status Codes

# Informational
from http.client import ACCEPTED
from site import USER_BASE

from zmq import CONNECT_TIMEOUT


INFORMATIONAL_CONTINUE = 100 
INFORMATIONAL_SWITCHING_PROTOCOL = 101
INFORMATIONAL_PROCESSING = 102
INFORMATIONAL_EARLY_HINTS = 103


#Success
SUCCESS_OK = 200 #(REST Specific)
SUCCESS_CREATED = 201 #(REST Specific)
SUCCESS_ACCEPTED = 202 #(REST Specific)
# SUCCESS_NON-AUTHORITATIVE_INFORMATION = 203
SUCCESS_NO_CONTENT = 204 #(REST Specific)
SUCCESS_RESET_CONTENT = 205
SUCCESS_PARTIAL_CONTENT = 206
SUCCESS_MULTI_STATUS = 207
SUCCESS_ALREADY_REPORTED = 208
SUCCESS_IM_USED = 226


#Redirection
REDIRECTION_MULTIPLE_CHOICES = 300
REDIRECTION_MOVED_PERMANENTLY = 301 #(REST Specific)
REDIRECTION_FOUND = 302 #(REST Specific)
REDIRECTION_SEE_OTHER = 303 #(REST Specific)
REDIRECTION_NOT_MODIFIED = 304 #(REST Specific)
REDIRECTION_USE_PROXY = 305
REDIRECTION_UNUSED = 306
REDIRECTION_TEMPORARY_REDIRECT = 307 #(REST Specific)
REDIRECTION_PERMANENT_REDIRECT = 308


#Client Error
CLIENT_ERROR_BAD_REQUEST = 400 #(REST Specific)
CLIENT_ERROR_UNAUTHORIZED = 401 #(REST Specific)
CLIENT_ERROR_PAYMENT_REQUIRED = 402
CLIENT_ERROR_FORBIDDEN = 403 #(REST Specific)
CLIENT_ERROR_NOT_FOUND = 404 #(REST Specific)
CLIENT_ERROR_METHOD_NOT_ALLOWED = 405 #(REST Specific)
CLIENT_ERROR_NOT_ACCEPTABLE = 406 #(REST Specific)
CLIENT_ERROR_PROXY_AUTHENTICATION_REQUIRED = 407
CLIENT_ERROR_REQUESTED_TIMEOUT = 408
CLIENT_ERROR_CONFLICT = 409
CLIENT_ERROR_GONE = 410
CLIENT_ERROR_LENGTH_REQUIRE = 411
CLIENT_ERROR_PRECONDITION_FAILED = 412 #(REST Specific)
CLIENT_ERROR_REQUEST_ENTITY_TOO_LARGE = 413
CLIENT_ERROR_REQUEST_URI_TOO_LONG = 414
CLIENT_ERROR_UNSUPPORTED_MEDIA_TYPE = 415
CLIENT_ERROR_REQUESTED_RANGE_NOT_SATISFIABLE = 416
CLIENT_ERROR_EXPECTATION_FAILED = 417


#Server Error
SERVER_ERROR_INTERNAL_SERVER_ERROR = 500 #(REST Specific)
SERVER_ERROR_OT_IMPLEMENTED = 501 #(REST Specific)
SERVER_ERROR_BAD_GATEWAY = 502
SERVER_ERROR_SERVICE_UNAVAILABLE = 503
SERVER_ERROR_GATEWAY_TIMEOUT = 504
SERVER_ERROR_HTTP_VERSION_NOT_SUPPORTED = 505
SERVER_ERROR_VARIANT_ALSO_NEGOTIATES = 506
SERVER_ERROR_INSUFFICIENT_STORAGE = 507 
SERVER_ERROR_LOOP_DETECTED = 508
SERVER_ERROR_NOT_EXTENDED = 510
SERVER_ERROR_NETWORK_AUTHENTICATED_REQUIRED = 511







# status

# Exist status
USER_EXIST = 10
EMAIL_EXIST = 11
USER_NAME_EXIST = 12
POSTS_EXIST = 13



# Created status
USER_CREATED = 20
PROFILE_CREATED = 21
POST_CREATED = 23

# Update status
USER_NAME_UPDATE = 30

# Not-Exist status
USER_NOT_EXIST = 40
USER_NAME_DOES_NOT_EXIST = 41
POSTS_NOT_EXIST = 42

# Selected status
USER_NAME_SELECTED = 50

# Not-Selected status
USER_NAME_NOT_SELECTED = 60

# change status
USER_NAME_CHANGE_SUCCESS = 70
USER_NAME_CHANGE_FAIL = 71
USER_ACTUAL_NAME_CHANGE_SUCCESS = 72
USER_ACTUAL_NAME_CHANGE_FAIL = 73
USER_BIO_CHANGE_SUCCESS = 74
USER_BIO_CHANGE_FAIL = 75
USER_PROFILE_PIC_CHANGE_SUCCESS = 76
USER_PROFILE_PIC_CHANGE_FAIL = 77
USER_PROFILE_VIEW_PERMISSION_CHANGE_SUCCESS = 78
USER_PROFILE_VIEW_PERMISSION_CHANGE_FAIL = 79


# Not created status
USER_NOT_CREATED = 80
PROFILE_NOT_CREATED = 81
POST_NOT_CREATED = 82

# connection
CONNECTION_CONNECTED = 91
CONNECTION_PENDING = 92
ALREADY_CONNECTED = 93




## connection status

PENDING = 0
ACCEPTED = 1
REJECTED = 2
BLOCKED = 3


def sayImported():
    print("#######################i am imported too")





